In [1]:
!pip install numpy

In [2]:
import numpy as np

# create arrays

arr1 = np.array([1,4,7,2])

In [4]:
print(arr1)
print(type(arr1))

[1 4 7 2]
<class 'numpy.ndarray'>


In [5]:
print(arr1.shape)

(4,)


In [7]:
arr2 = np.array([1,4,7,9,4])
arr2.reshape(1,5)   # 1 row and 5 columns

array([[1, 4, 7, 9, 4]])

In [10]:
# 2D array
arr2 = np.array([[9,8,7,6,5],[1,3,5,7,9]])
print(arr2.shape)
print(arr2)

(2, 5)
[[9 8 7 6 5]
 [1 3 5 7 9]]


In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
# identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
# numpy vector operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# element wise addition
print('Addition', arr1 + arr2)

# subtraction
print('Substraction', arr1 - arr2)

# multiply
print('Multiplication', arr1 * arr2)

# division
print('Division', arr1 / arr2)

Addition [11 22 33 44 55]
Substraction [ -9 -18 -27 -36 -45]
Multiplication [ 10  40  90 160 250]
Division [0.1 0.1 0.1 0.1 0.1]


In [16]:
# universal function
arr = np.array([2,3,4,5,6])

# square root
print(np.sqrt(arr))

# expo
print(np.exp(arr))

# sine
print(np.sin(arr))

# natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [18]:
# slicing and indexing

arr = np.array([[1,2,3,4,5], [1,3,5,7,9], [9,8,7,6,5]])
print(arr)

[[1 2 3 4 5]
 [1 3 5 7 9]
 [9 8 7 6 5]]


In [22]:
arr[2,1]

np.int64(8)

In [23]:
arr[0][1]

np.int64(2)

In [24]:
arr[1:]

array([[1, 3, 5, 7, 9],
       [9, 8, 7, 6, 5]])

In [25]:
arr[2:]

array([[9, 8, 7, 6, 5]])

In [26]:
arr[1:,2:]

array([[5, 7, 9],
       [7, 6, 5]])

In [28]:
print(arr[0:2, 2:])

[[3 4 5]
 [5 7 9]]


In [29]:
# modifying elements
arr[0,0] = 55
print(arr)

[[55  2  3  4  5]
 [ 1  3  5  7  9]
 [ 9  8  7  6  5]]


In [30]:
arr[1:] = 41
print(arr)

[[55  2  3  4  5]
 [41 41 41 41 41]
 [41 41 41 41 41]]


In [31]:
# normalization
# mean of 0 and Standard deviation of 1

data = np.array([1,4,2,7,9])

# calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# normalize the data
norm_data = (data - mean) / std_dev
print('Normalized Data: ', norm_data)

Normalized Data:  [-1.19734219 -0.19955703 -0.86474714  0.79822813  1.46341823]


In [32]:
data = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

# Mean
mean = np.mean(data)
print(mean)

# Median
median = np.median(data)
print(median)

# Standard Deviation
std_dev = np.std(data)
print(std_dev)

# Variance
var = np.var(data)
print(var)

8.0
8.0
4.320493798938574
18.666666666666668


In [37]:
# logical operations

data = np.array([1,3,5,7,9,11,13,15])

data [(data > 6) & (data < 15)]

array([ 7,  9, 11, 13])